=== clinicaldocumentengineering/OpenCDEViewer/src/config/Preferences.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    File: Preferences.xsd
    Created: April 2016
    Authors: Martí Pàmies / Rafael Rosa
    Description: OpenCDE Viewer Preferences file XML schema
--> 
<!--
 Licensed to Clinical Document Engineering (CDE) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 CDE licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  elementFormDefault="qualified" 
  targetNamespace="http://clinicaldocumentengineering.com/OpenCDE" 
  xmlns:opencde="http://clinicaldocumentengineering.com/OpenCDE">
  
  <!-- Root element -->
  <xs:element name="Preferences">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="opencde:DocumentsCodesPreferences"/>
        <xs:element ref="opencde:DICOMViewer"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- For a particular type of document preferences -->
  <xs:element name="DocumentsCodesPreferences">
    <xs:complexType>
      <xs:sequence>
        <!-- Initial sections -->
        <xs:element minOccurs="0" ref="opencde:DocumentCodeInitialSections"/>
        <!-- Sections relations -->
        <xs:element minOccurs="0" ref="opencde:SectionsRelations"/>
        <!-- Auto search keywords -->
        <xs:element minOccurs="0" ref="opencde:SearchKeyWords"/>
      </xs:sequence>
      <!-- To define the type of document -->
      <xs:attribute name="code" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="codeSystem" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  
  <!-- Initial sections to be displayed -->
  <xs:element name="DocumentCodeInitialSections">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="opencde:Section"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- To define initial sections using code and codeSsytem -->
  <xs:element name="Section">
    <xs:complexType>
      <xs:attribute name="code" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="codeSystem" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  
  <!-- To define sections relations -->
  <xs:element name="SectionsRelations">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="opencde:SectionRelation"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- A particular section relation -->
  <xs:element name="SectionRelation">
    <xs:complexType>
      <xs:sequence>
        <!-- Source (where the link is added) -->
        <xs:element ref="opencde:SourceSection"/>
        <!-- Target ( Where the link will navigate) -->
        <xs:element ref="opencde:TargetSection"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- Source (where the link is added) -->
  <xs:element name="SourceSection">
    <xs:complexType>
      <xs:attribute name="code" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="codeSystem" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  
  <!-- Target ( Where the link will navigate) -->
  <xs:element name="TargetSection">
    <xs:complexType>
      <xs:attribute name="code" use="required" type="xs:NMTOKEN"/>
      <xs:attribute name="codeSystem" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  
  <!-- To goup all search key words for a type of document -->
  <xs:element name="SearchKeyWords">
    <xs:complexType>
      <xs:sequence>
        <!-- Key word to be searched -->
        <xs:element maxOccurs="unbounded" name="KeyWord" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- DICOM Viewer integration preferences -->
  <xs:element name="DICOMViewer">
    <xs:complexType>
      <xs:sequence>
        <!-- Type of viewer -->
        <xs:element name="ViewerType" type="opencde:ViewerTypeCT"/>
        <!-- Viewer specific parameters -->
        <xs:element name="ViewerParameters" type="opencde:ViewerParametersCT"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- Enumeration of allowed Viewers -->
  <xs:simpleType name="ViewerTypeCT">
    <xs:restriction base="xs:string">
      <!-- DICOM Web Viewer (https://github.com/ivmartel/dwv) -->
      <xs:enumeration value="DWV"></xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- Viewer parameters properties bag -->
  <xs:complexType name="ViewerParametersCT">
    <xs:sequence>
      <xs:element name="Parameter" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Value" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>      
    </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== clinicaldocumentengineering/OpenCDEViewer/src/config/Preferences.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    File: Preferences.xml
    Created: April 2016
    Authors: Martí Pàmies / Rafael Rosa
    Description: OpenCDE Viewer Preferences file, to configure some features
--> 
<!--
 Licensed to Clinical Document Engineering (CDE) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 CDE licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<Preferences xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://clinicaldocumentengineering.com/OpenCDE Preferences.xsd"
    xmlns="http://clinicaldocumentengineering.com/OpenCDE">
    <!-- Per each type of document preferences -->
    <!-- LOINC 34133-9: Summary of episode note -->
    <DocumentsCodesPreferences code="34133-9" codeSystem="2.16.840.1.113883.6.1">
        <!-- Initial sections to be displayed -->
        <DocumentCodeInitialSections>
            <!--Reason for visit-->
            <Section code="29299-5" codeSystem="2.16.840.1.113883.6.1"/>
            <!-- Plan of Care -->
            <Section code="18776-5" codeSystem="2.16.840.1.113883.6.1"/>
            <!--Instructions-->
            <Section code="69730-0" codeSystem="2.16.840.1.113883.6.1"/>
        </DocumentCodeInitialSections>
        <!-- Related sections -->
        <SectionsRelations>
            <SectionRelation>
                <!-- Medications -->
                <SourceSection code="10160-0" codeSystem="2.16.840.1.113883.6.1"/>
                <!--Allergies, adverse reactions, alerts-->
                <TargetSection code="48765-2" codeSystem="2.16.840.1.113883.6.1"/>
            </SectionRelation>
        </SectionsRelations>
        <!-- Key words to be searched automatically when opening that type of document -->
        <SearchKeyWords>
            <KeyWord>Penicillin</KeyWord>
        </SearchKeyWords>
    </DocumentsCodesPreferences>
    <!-- LOINC 52521-2: Plan of Care -->
    <DocumentsCodesPreferences code="52521-2" codeSystem="2.16.840.1.113883.6.1">
        <!-- Initial sections to be displayed -->
        <DocumentCodeInitialSections>
            <!-- Goals Section -->
            <Section code="61146-7" codeSystem="2.16.840.1.113883.6.1"/>
            <!-- Health Status Evaluations/Outcomes Section  -->
            <Section code="11383-7" codeSystem="2.16.840.1.113883.6.1"/>
        </DocumentCodeInitialSections>
    </DocumentsCodesPreferences>
    <!-- DICOM Viewer Parameters -->
    <DICOMViewer>
        <!--Viewer Type -->
        <ViewerType>DWV</ViewerType>
        <ViewerParameters>
            <!-- Viewer Specific parameters -->
            <Parameter>
                <Name>URL</Name>
                <Value>http://ivmartel.github.io/dwv/demo/stable/viewers/mobile/index.html?input=</Value>
            </Parameter>
        </ViewerParameters>
    </DICOMViewer>
</Preferences>
